server:
  port: 8089
  context-path: /


spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://10.248.178.67:3306/db_film
      username: root
      password: root
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false


imageFilePath: /Users/mac/Documents/IDEA-workspace/Film/src/main/webapp/static/filmImage/
